{% set name = "beem" %}
{% set version = "0.19.27" %}
{% set sha256 = "ae28e6ac72668936860bffcb0e51a9a192d1d6dc79e7f9d02bb4b019058c96b5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256|lower }}

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - pytest-runner
    - setuptools
  run:
    - python
    - future
    - ecdsa
    - requests
    - websocket-client
    - appdirs
    - events
    - scrypt
    - pycryptodomex
    - pytz
    - six
    - prettytable
    - click
    - cryptography

test:
  imports:
    - beem
    - beem.account
    - beem.amount
    - beem.comment
    - beem.market
    - beem.aes
    - beem.block
    - beem.blockchain
    - beem.cli
    - beem.message
    - beem.notify
    - beem.instance
    - beem.price
    - beem.steem
    - beem.transactionbuilder
    - beem.utils
    - beem.vote
    - beem.witness

about:
  home: https://github.com/holgern/beem
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  dev_url: https://github.com/holgern/beem
  doc_url: http://beem.readthedocs.io/en/latest/
  summary: 'beem is an unofficial python library for steem.'

extra:
  recipe-maintainers:
    - holgern
