travis:
  secure:
    BINSTAR_TOKEN: oCBqNMdhpflG2oVWp7+BC4X7HZx26OvZKXn/ri5ZSOnvPNII5FtmK0aaXwe6oN05B4+vUFpXTkgsacc3K1n06xkmEk8KkEpoBJXTBk2Z29N6IC+GMIaynsMeSf/KrnLl6fTUXOLa9zlzrUPMfNZQMlcsAdIXLujk/3u9gnG4F4Qo/1Ukg3DqkdC05tTouA6cvohNFVLYb+o9gHUf6Fh5YDQfdmtkhZJUzFKhEMcH1jbJU3FedQVjxL50+CE/RZEQngs9uGq27TveSy4oCv2vwTT4l0mkcmRWkkYVE+kgvpdv+b9xWVM+eA1JHDF5T0THYuhmHLQmOSCdjQQ5v0OBrtqty3o06n6TxXbrv9FiOyeU5XWBUepKJHvud+LnCiF8ad+5knQMhWTnzgHBU62gHF4vt9PXBpJXOtmQNkg/WOUI9a80lFXxZVXBPqGpp5qJJXE5nVLRkEu4a9B76xNEPhGwSrsJutrnnbjQUL0Pc8GWmDNzXBQHlqnYbp+jkDO2p2hQROKHdg8BmG/v+WiPj8fHfZ2fjD4PMeu8SN9jorDDf/+CRnsvQf+btjm5qh8HQ85XpXbpDVmoBxhus1GD6gPN6yLTjRC6+1hktl6DwbnZJo66cwBqSFHDmcMfP8dZkm35W9y7Johig0Xwp3j59d8jaAyPFacDej0+Gpxl8Xg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
